In [1]:
import numpy as np

from svd import svd_decomposition

In [2]:
A = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], dtype = float
)

In [3]:
U, Sigma, Vt = svd_decomposition(A)

In [7]:
print("Our SVD results:")
print(f"U: \n{U}")
print(f"Sigma: \n{Sigma}")
print(f"Vt: \n{Vt}")

Our SVD results:
U: 
[[-0.21483724  0.88723071 -0.40824828]
 [-0.52058739  0.249644    0.81649661]
 [-0.82633754 -0.38794271 -0.40824824]]
Sigma: 
[[16.84810335  0.          0.        ]
 [ 0.          1.06836951  0.        ]
 [ 0.          0.          0.        ]]
Vt: 
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [ 0.40824829 -0.81649658  0.40824829]]


In [8]:
A_reconstructed = np.dot(U, np.dot(Sigma, Vt))

In [9]:
print("Reconstructed A:")
print(A_reconstructed)

Reconstructed A:
[[0.99999999 2.         3.00000002]
 [3.99999996 5.         6.00000003]
 [6.99999994 7.99999999 9.00000005]]


In [10]:
error = np.linalg.norm(A - A_reconstructed, 'fro')
print(f"Reconstruction error: ")
print(f"{error:.2e}")

Reconstruction error: 
9.24e-08
